// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/route/{namespace}/{routeName}": {
            "get": {
                "description": "Returns details for an API HttpRoute",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HTTPRoute"
                ],
                "summary": "Gets HTTPRoute object",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace to search",
                        "name": "namespace",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "HTTPRoute resource name being searched",
                        "name": "routeName",
                        "in": "path"
                    },
                    {
                        "type": "boolean",
                        "description": "decides if it adds Deployment data related to the route",
                        "name": "include_deployment",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Applies a label selector to k8s API query in format label_name=value,label_name2,value2",
                        "name": "label_selectoor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/routes": {
            "get": {
                "description": "Returns a list of Gateway API HttpRoutes matching criteria",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HTTPRoute"
                ],
                "summary": "List HTTPRoute objects",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace to search (default)",
                        "name": "namespace",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "decides if it adds Deployment data related to the route",
                        "name": "include_deployment",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Applies a label selector to k8s API query in format label_name=value,label_name2,value2",
                        "name": "label_selector",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "RouteAPI",
	Description:      "API to query HTTPRoutes and related Gateway API resources.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
