basePath: /api
info:
  contact: {}
  description: API to query HTTPRoutes and related Gateway API resources.
  license:
    name: MIT
  title: RouteAPI
  version: 0.0.1
paths:
  /route/{namespace}/{routeName}:
    get:
      description: Returns details for an API HttpRoute
      parameters:
      - description: Namespace to search
        in: path
        name: namespace
        type: string
      - description: HTTPRoute resource name being searched
        in: path
        name: routeName
        type: string
      - description: decides if it adds Deployment data related to the route
        in: query
        name: include_deployment
        type: boolean
      - description: Applies a label selector to k8s API query in format label_name=value,label_name2,value2
        in: query
        name: label_selectoor
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Gets HTTPRoute object
      tags:
      - HTTPRoute
  /routes:
    get:
      description: Returns a list of Gateway API HttpRoutes matching criteria
      parameters:
      - description: Namespace to search (default)
        in: query
        name: namespace
        type: string
      - description: decides if it adds Deployment data related to the route
        in: query
        name: include_deployment
        type: boolean
      - description: Applies a label selector to k8s API query in format label_name=value,label_name2,value2
        in: query
        name: label_selector
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: List HTTPRoute objects
      tags:
      - HTTPRoute
swagger: "2.0"
