components:
  schemas:
    internal_api.APIResponse:
      properties:
        data: {}
        error: {}
        message:
          type: string
        statusCode:
          type: integer
        success:
          type: boolean
      type: object
externalDocs:
  description: ""
  url: ""
info:
  description: Exposes API Gateway routes and deployments attached to them
  title: routeapi
  version: "0.2"
openapi: 3.1.0
paths:
  /health/:
    get:
      description: health status
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_api.APIResponse'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_api.APIResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_api.APIResponse'
          description: Internal Server Error
      summary: Health status
  /route/{namespace}/{routeName}:
    get:
      description: Queries API Gateway HTTP Route object
      parameters:
      - description: Namespace to search for params
        in: path
        name: namespace
        required: true
        schema:
          type: string
      - description: 'Label string to match selector: comma separated values of type
          key=value'
        in: path
        name: routeName
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_api.APIResponse'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_api.APIResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_api.APIResponse'
          description: Internal Server Error
      summary: Retrieves details of a specific route
  /routes/:
    get:
      description: Queries API Gateway HTTP Route objects based on criteria
      parameters:
      - description: Namespace to search for params
        in: query
        name: namespace
        required: true
        schema:
          type: string
      - description: 'Label string to match selector: comma separated values of type
          key=value'
        in: query
        name: label_selector
        schema:
          type: string
      - description: Flag to indicate if response should include deployment data for
          each route
        in: query
        name: include_deployment
        schema:
          type: boolean
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_api.APIResponse'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_api.APIResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_api.APIResponse'
          description: Internal Server Error
      summary: Retrieves a list of routes matching criteria
servers:
- url: /api
