name: Test routeAPI by installing it in a kind cluster
on:
  push:
    branches:
      - test/*
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

# installs kind cluster
      - name: Setup Kubernetes
        uses: helm/kind-action@v1.14.0
        with:
          cluster_name: routeapi

# installs traefik to implement API Gateway routing
      - name: Install traefik
        run: |
          helm repo add traefik https://traefik.github.io/charts
          helm repo update
          helm install traefik traefik/traefik -f test/scripts/traefik-values.yaml -n traefik --create-namespace --version 37.3.0
# installs applications
      - name: Build application and load image into kind cluster
        run: |
          docker build -t routeapi:test .
          kind load docker-image routeapi:test
      
      - name: Install app in cluster
        run: |
          kubectl apply -f manifests/rbac.yaml
          sed -i -e "s/image\:.*$/image:\ routeapi:test/" manifests/deployment.yaml 
          kubectl apply -f manifests/deployment.yaml
          kubectl wait deployment/routeapi --for=condition=ready --timeout 30s
      
      - name: Install sample app and routes
        run: |
          kubectl apply -f test/scripts/applications.yaml
          kubectl apply -f test/scripts/routes.yaml
          kubectl port-forward svc/routeapi 8080:8080 &
          curl "http://127.0.0.1:8080/api/routes?namespace=traefik"
          curl "http://127.0.0.1:8080/api/route/traefik/weight-route"|jq
